#pragma once

#define ORIGIN		Director::getInstance()->getVisibleOrigin()
#define SIZE		Director::getInstance()->getVisibleSize()

// 标签
#define BACKGROUND_TAG_1		1
#define BACKGROUND_TAG_2		2
#define HERO_TAG 3
#define LABEL_SCORE_TAG			10
#define UFO_TAG_1				20

// ZORDER
#define BACKGROUND_ZORDER		-1
#define DEFAULT_ZORDER			0
#define FOREGROUND_ZORDER		1
#define UI_ZORDER				99

// 速度
#define BACKGROUND_SPEED		1.5f
#define BULLET_SPEED			6.0f
#define SMALL_ENEMY_SPEED		4.5f
#define MIDDLE_ENEMY_SPEED		4
#define BIG_ENEMY_SPEED			2.5f

// 血量
#define SMALL_ENEMY_HEALTH		100
#define MIDDLE_ENEMY_HEALTH		450
#define BIG_ENEMY_HEALTH		800
#define HERO_DAMAGE				100

// 分数
#define SMALL_ENEMY_SCORE		1
#define MIDDLE_ENEMY_SCORE		4
#define BIG_ENEMY_SCORE			6

// 定时器间隔
#define CREATE_BULLET_INTERVAL				0.3f
#define CREATE_SMALLENEMY_INTERVAL			2.0f
#define CREATE_MIDDLEENEMY_INTERVAL			8.0f
#define CREATE_BIGENEMY_INTERVAL			18
#define CREATE_UFO_1_INTERVAL				10
#define CREATE_SMALLENEMY_DELAY				3
#define CREATE_MIDDLEENEMY_DELAY			10
#define CREATE_BIGENEMY_DELAY				30.0f

// 动画播放时间
#define LOADING_TIME_PER_FRAME				0.25f
#define HERO_FLy_TIME_PER_FRAME				0.2f
#define ENEMY_EXPLODE_TIME_PER_FRAME		0.2f
#define ENEMY_FLY_ANIMATION_TIME_PER_FRAME	0.2f
#define ENEMY_HIT_ANIMATION_TIME_PER_FRAME	0.1f

// 动画缓存槽
#define HERO_FLY_ANIMATION				"HERO_FLY"
#define HERO_DIE_ANIMATION				"HERO_DIE"
#define SMALLENEMY_EXPLODE_ANIMATION	"SMALLENEMY_EXPLODE"
#define MIDDLEENEMY_HIT_ANIMATION		"MIDDLEENEMY_HIT"
#define MIDDLEENEMY_EXPLODE_ANIMATION	"MIDDLEENEMY_EXPLODE"
#define BIGENEMY_FLY_ANIMATION			"BIGENEMY_FLY"
#define BIGENEMY_HIT_ANIMATION			"BIGENEMY_HIT"
#define BIGENEMY_EXPLODE_ANIMATION		"BIGENEMY_EXPLODE"

// 键值对-键名
#define HIGH_SCORE_KEY "HighScore"