#pragma once

// 速度
#define BACKGROUND_SPEED_DEFAULT		1.5f
#define BULLET_SPEED_DEFAULT			6.0f
#define SMALL_ENEMY_SPEED_DEFAULT		4.5f
#define MIDDLE_ENEMY_SPEED_DEFAULT		4.0f
#define BIG_ENEMY_SPEED_DEFAULT		2.5f

// 血量
#define SMALL_ENEMY_HEALTH_DEFAULT		100
#define MIDDLE_ENEMY_HEALTH_DEFAULT		450
#define BIG_ENEMY_HEALTH_DEFAULT		800
#define HERO_DAMAGE_DEFAULT				100

// 分数
#define SMALL_ENEMY_SCORE_DEFAULT		1
#define MIDDLE_ENEMY_SCORE_DEFAULT		4
#define BIG_ENEMY_SCORE_DEFAULT			6

// 定时器间隔
#define CREATE_BULLET_INTERVAL_DEFAULT				0.3f
#define CREATE_SMALLENEMY_INTERVAL_DEFAULT			2.0f
#define CREATE_MIDDLEENEMY_INTERVAL_DEFAULT			8.0f
#define CREATE_BIGENEMY_INTERVAL_DEFAULT			18
#define CREATE_UFO_1_INTERVAL_DEFAULT				10
#define CREATE_SMALLENEMY_DELAY_DEFAULT				3
#define CREATE_MIDDLEENEMY_DELAY_DEFAULT			10
#define CREATE_BIGENEMY_DELAY_DEFAULT				30.0f