#pragma once
// 颜色 （白色为0,蓝色为1,红色为2）
#define HERO_COLOR_DEFAULT  0

// 速度
#define BACKGROUND_SPEED_DEFAULT		1.5f
#define BULLET_SPEED_DEFAULT			600.0f


#define SMALL_ENEMY_SPEED_DEFAULT		4.5f
#define MIDDLE_ENEMY_SPEED_DEFAULT		4.0f
#define BIG_ENEMY_SPEED_DEFAULT			2.5f
#define BULLET_FLASH_SPEED_DEFAULT		500.0f


// 血量
#define SMALL_ENEMY_HEALTH_DEFAULT		100
#define MIDDLE_ENEMY_HEALTH_DEFAULT		350
#define BIG_ENEMY_HEALTH_DEFAULT		600
#define HERO_DAMAGE_DEFAULT				100

// 分数
#define SMALL_ENEMY_SCORE_DEFAULT		1
#define MIDDLE_ENEMY_SCORE_DEFAULT		4
#define BIG_ENEMY_SCORE_DEFAULT			6

// 定时器间隔
#define CREATE_BULLET_INTERVAL_DEFAULT				0.025f
#define CREATE_SMALLENEMY_INTERVAL_DEFAULT			2.0f
#define CREATE_MIDDLEENEMY_INTERVAL_DEFAULT			8.0f
#define CREATE_BIGENEMY_INTERVAL_DEFAULT			18
#define CREATE_UFO_1_INTERVAL_DEFAULT				10
//#define CREATE_SORMENEMYBYBIGENEMY_INTERVAL_DEFAULT	19
#define CREATE_SMALLENEMY_DELAY_DEFAULT				3
#define CREATE_MIDDLEENEMY_DELAY_DEFAULT			10
#define CREATE_BIGENEMY_DELAY_DEFAULT				30.0f
//#define CREATE_SORMENEMYBYBIGENEMY_DELAY_DEFAULT	30.0f