#pragma once
#define DEFAULT_CONSTANT 3306

// 速度
#define BACKGROUND_SPEED_DEFFAULT		1.5f
#define BULLET_SPEED_DEFFAULT			6.0f
#define SMALL_ENEMY_SPEED_DEFFAULT		4.5f
#define MIDDLE_ENEMY_SPEED_DEFFAULT		4.0f
#define BIG_ENEMY_SPEED_DEFFAULT		2.5f

// 血量
#define SMALL_ENEMY_HEALTH_DEFFAULT		100
#define MIDDLE_ENEMY_HEALTH_DEFFAULT		450
#define BIG_ENEMY_HEALTH_DEFFAULT		800
#define HERO_DAMAGE_DEFFAULT				100

// 分数
#define SMALL_ENEMY_SCORE_DEFFAULT		1
#define MIDDLE_ENEMY_SCORE_DEFFAULT		4
#define BIG_ENEMY_SCORE_DEFFAULT			6

// 定时器间隔
#define CREATE_BULLET_INTERVAL_DEFFAULT				0.3f
#define CREATE_SMALLENEMY_INTERVAL_DEFFAULT			2.0f
#define CREATE_MIDDLEENEMY_INTERVAL_DEFFAULT			8.0f
#define CREATE_BIGENEMY_INTERVAL_DEFFAULT			18
#define CREATE_UFO_1_INTERVAL_DEFFAULT				10
#define CREATE_SMALLENEMY_DELAY_DEFFAULT				3
#define CREATE_MIDDLEENEMY_DELAY_DEFFAULT			10
#define CREATE_BIGENEMY_DELAY_DEFFAULT				30.0f